Repository 7-7-2/DDocker_BE, pull requests merged in 2024-01, with the labels that each got.

#4 getPostDetail 및 mysql2 migration입니다.
  config/index.js
  controllers/posts-controller.js
  loaders/db.js
  models/posts-db.js
  package.json
  pnpm-lock.yaml
  routes/posts-route.js
  services/post-service.js
Labels: documentation

#5 feat: brand data fetched
  controllers/brand-controller.js
  models/brand-db.js
  package.json
  routes/brand-route.js
  services/brand-service.js
Labels: 🚧 기능구현, 🚀 완료

#9 Feat: postRegister
  controllers/posts-controller.js
  loaders/db.js
  models/posts-db.js
  routes/posts-route.js
  services/post-service.js
Labels: 🚀 완료

#21 Feat: deleteComment/replyComment/deleteReply
  controllers/posts-controller.js
  middlewares/buildPatchQuery.js
  models/posts-db.js
  models/posts-queries.js
  routes/posts-route.js
  services/post-service.js
  swagger-output.json
Labels: 🚧 기능구현, 🚀 완료
