Repository 7-7-2/DDocker_BE, pull requests merged in 2024-05, with the labels that each got.

#102 Feat: getWeeklyPopularList && date
  controllers/posts-controller.js
  models/posts-queries.js
Labels: 🚧 기능구현, 🚀 완료

#105 Feat: deleteUserAccount.api
  controllers/user-controller.js
  models/user-db.js
  routes/users-route.js
  services/user-service.js
Labels: 🚧 기능구현, 🚀 완료

#106 Feat: postReport api
  controllers/report-controller.js
  models/report-db.js
  routes/report-route.js
  services/report-service.js
Labels: 🚧 기능구현, 🚀 완료

#108 Fix: setUserInit api
  controllers/user-controller.js
  models/user-db.js
  services/user-service.js
Labels: 🔥 Fix, 🚀 완료

#114 Fix: setUserOauth && Remove default profile Image
  models/user-db.js
  services/user-service.js
Labels: 🔥 Fix, 🚀 완료

#118 feat: remove getUserProfile
  controllers/user-controller.js
  models/user-db.js
  routes/users-route.js
  services/user-service.js
Labels: 🚀 완료

#122 feat: cache brand data with Redis
  controllers/brand-controller.js
  loaders/index.js
  loaders/redis.js
  models/brand-db.js
  models/brand-queries.js
Labels: 🚧 기능구현, 🚀 완료

#128 Feat: add heartbeat interval to keep notification connection
  controllers/notification-controller.js
Labels: 🚧 기능구현, 🚀 완료

#130 feat: set up CI/CD
  .github/workflows/deploy.yaml
  config/index.js
  package.json
  pnpm-lock.yaml
Labels: 🚀 완료

#132 Fix: deploy script
  .github/workflows/deploy.yaml
Labels: 🔥 Fix

#133 Fix: deploy scenario
  .github/workflows/deploy.yaml
Labels: 🔥 Fix

#135 Fix: script mysql root access
  .github/workflows/deploy.yaml
Labels: 🔥 Fix

#137 feat: add new brands in brandMap
  middlewares/switchBrand.js
Labels: 🚧 기능구현

#139 fix: specify notification access control allow origin
  controllers/notification-controller.js
Labels: 🔥 Fix
